ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_top_alphaScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_551 = ', GC_551
      WRITE(*,2) 'GC_554 = ', GC_554
      WRITE(*,2) 'GC_687 = ', GC_687
      WRITE(*,2) 'GC_690 = ', GC_690
